server:
  port: 8080

spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:  
          uri: https://git.oschina.net/itmuch/spring-cloud-config-repo # 配置Git仓库的地址
          username: dengsaiyun@163.com  # Git仓库的账号
          password: Hello2016   # Git仓库的密码


