spring:
  application:
    name: microservice-consumer-movie-without-eureka

server:
  port: 8010
  
microservice-simple-provider-user:
  ribbon:
    listOfServers: localhost:8000,localhost:8001