spring:
  application:
    name: microservice-consumer-movie-feign-customizing

server:
  port: 8010
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true