server:
  port: 8000
  
spring:
  application:
    name: microservice-provider-user-my-metadata
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    platform: h2
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://127.0.0.1/E:/repository/database/h2/test_db
    schema: classpath:schema.sql
    data: classpath:data.sql
    username: sa
    password: sa123
  
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRANCE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRANCE
    
management:
  security:
    enabled: false
    
eureka:
  client:
    service-url:
      # defaultZone: http://peer1:8761/eureka,http://peer2:8762/eureka
      # defaultZone: http://admin:admin@localhost:8761/eureka
      defaultZone: http://localhost:8761/eureka
  instance:
    # 将自己的IP注册到Eureka Server,如不配置,默认为false,则表示注册该微服务所在操作系统的hostname到Eureka Server
    prefer-ip-address: true
    metadata-map:
      my-metadata: 我自定义的元数据